In [17]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from IPython.display import display, Markdown

from sklearn.datasets import load_iris
iris = load_iris()
data = pd.DataFrame(data=np.c_[iris['data'], iris['target']], columns=iris['feature_names'] + ['target'])

print("This program demonstrates the use of a Naive Bayes model for Iris flower classification.")
print("The model is trained on the Iris dataset, a well-known dataset for multi-class classification tasks.")
print("The dataset contains features such as sepal length, sepal width, petal length, and petal width,")
print("and the task is to predict the species of iris flowers.\n")

display(data.head())

display(Markdown("## Naive Bayes Classifier\n" ))

X = iris.data
y = iris.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = GaussianNB()

model.fit(X_train, y_train)

user_input = []
for i in range(X.shape[1]):
    feature_value = float(input(f"Enter value for {iris.feature_names[i]}: "))
    user_input.append(feature_value)

user_input = np.array(user_input).reshape(1, -1)
prediction = model.predict(user_input)

print(f"\nPredicted species: {iris.target_names[int(prediction)]}")

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"\nAccuracy: {accuracy:.2f}")

class_report = classification_report(y_test, y_pred, target_names=iris.target_names)
print("\nClassification Report:\n", class_report)

conf_matrix = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:\n", conf_matrix)

conf_matrix_df = pd.DataFrame(conf_matrix, columns=iris.target_names, index=iris.target_names)
display(conf_matrix_df)


This program demonstrates the use of a Naive Bayes model for Iris flower classification.
The model is trained on the Iris dataset, a well-known dataset for multi-class classification tasks.
The dataset contains features such as sepal length, sepal width, petal length, and petal width,
and the task is to predict the species of iris flowers.



sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)   
0                5.1               3.5                1.4               0.2  \
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0

## Naive Bayes Classifier


Enter value for sepal length (cm):  4
Enter value for sepal width (cm):  5
Enter value for petal length (cm):  6
Enter value for petal width (cm):  7



Predicted species: virginica

Accuracy: 1.00

Classification Report:
               precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30


Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


setosa  versicolor  virginica
setosa          10           0          0
versicolor       0           9          0
virginica        0           0         11